# Generated by Django 5.0.3 on 2024-05-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userprofile_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created']},
        ),
    ]
