# Generated by Django 5.0.3 on 2024-05-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_posts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='defaultprofile.jpg', upload_to='media'),
        ),
    ]
