# Generated by Django 5.0.3 on 2024-05-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default="Hey! I'm Gonna Shoot you :D", max_length=50),
        ),
    ]
